services:
  gcloud:
    image: google/cloud-sdk:latest
    volumes:
      - "gcp:/root/.config/"
    entrypoint: gcloud

  dev:
    image: gfw/pipe-anchorages-dev
    build:
      context: .
      target: dev
    volumes:
      - ".:/opt/project"
      - "gcp:/root/.config/"
    entrypoint: "pipe-anchorages"

  test:
    # Runs tests using the production Docker image.
    # Intended to be executed in the GitHub CI environment.
    build:
      context: .
      target: test
    entrypoint: "pytest -v"

# Volume to hold GCP authentication
volumes:
  gcp:
    external: true